[tools]
github-cli = "latest"
go = "latest"
"go:github.com/cweill/gotests/gotests" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:github.com/matryer/moq" = "latest"
golangci-lint = "latest"
"npm:cspell" = "latest"
task = "latest"
